---
kubernetes_haproxy_config: >
  frontend kubernetes-frontend
          bind 172.16.16.100:6443
          mode tcp
          option tcplog
          default_backend kubernetes-backend
  backend kubernetes-backend
          mode tcp
          option tcp-check
          balance roundrobin
          server kmaster1 172.16.16.101:6443 check fall 3 rise 2
          server kmaster2 172.16.16.102:6443 check fall 3 rise 2
      