apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubab.fullname" . }}
spec:
  type: NodePort
  selector:
    {{- include "kubab.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: 8080