---
- name: Disable swap
  shell: >
    swapoff -a; sed -i '/swap/d' /etc/fstab 

# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
# Of course there is no need to add this task because we use Debian 10.
- name: Let iptables see bridged traffic.
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

  
- name: Install Docker engine prerequisites
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

# - name: Add Docker's official GPG key
#   shell: >
#     curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
- name: Add Docker's official GPG key
  apt_key:
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

# Output of lsb_release might be like 'buster', 'stretch' and 'jessie'      
- name: Get distribution name
  command: >
    lsb_release -cs
  register: lsb_release  
  
- name: Add Docker apt repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ lsb_release.stdout }} stable"
    state: present
    update_cache: true

- name: Install Docker
  apt:
    name:
      - docker-ce=5:19.03.10~3-0~debian-{{ lsb_release.stdout  }} 
      - containerd.io
    state: present
  # notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: true 